config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  match '/signup', to: 'users#new',          via: 'get'
  match '/signup', to: 'users#create',       via: 'post'
  match '/login',  to: 'sessions#new',       via: 'get'
  match '/login',  to: 'sessions#create',    via: 'post'
  match '/logout', to: 'sessions#destroy',   via: 'delete'

  resources :comments

  resources :users do
    resources :comments
  end

  resources :books do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  default_scope -> { order('updated_at DESC') }
  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 3, maximum: 250 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_author, only: [:edit, :update]
  before_action :comment_del,    only: :destroy

  def new
    book_id = params[:book_id]
    @book = Book.find(book_id)
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = "The comment is successfully added"
      redirect_to (book_path(@comment.book_id))
    else
      book_id = params[:comment][:book_id]
      @book = Book.find(book_id)
      render 'new'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      flash[:success] = "Comment updated"
      redirect_to @comment.book
    else
      render 'edit'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:success] = "Comment deleted"
    redirect_to root_url
  end

  private

    def comment_params
      params.require(:comment).permit(:book_id, :user_id, :content)
    end

    def author_comment
      @comment = Comment.find(params[:id])
      @comment_user = @comment.user
    end

    def correct_author
      author_comment
      redirect_to(root_url) unless current_user?(@comment_user)
    end

    def comment_del
      author_comment
      redirect_to(root_url) unless current_user?(@comment_user) || current_user.admin?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def i_author?(comment)
    comment.user == current_user
  end

end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-user">
    <span class="glyphicon glyphicon-user"></span> <%= "#{comment.user.name}" %>
  </p>
  <p class="comment-content">
    <span class="glyphicon glyphicon-comment"></span> <%= "#{comment.content}" %>
  </p>
  <p class="nav-comment">
    <% if i_author?(comment) %>
      <%= link_to "Edit", edit_comment_path(comment), class: "btn btn-warning btn-xs" %>
    <% end %>

    <% if i_author?(comment) || current_user.admin? %>
      <%= link_to "Delete", comment, controller: :comments, method: :delete,
                                data: { confirm: "You sure?" },
                                class: 'btn btn-danger btn-xs'  %>
    <% end %>
  </p>
</div>

app/views/comments/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :comment %>
<%= f.text_area :content %>

app/views/comments/edit.html.erb
<% provide(:title, 'Edit Comment') %>

<div class="row">
  <div class="col-md-12">
      <h1 class="book-name-show">
        <span class="glyphicon glyphicon-book"></span> <%= "#{@comment.book.name}" %>
      </h1>
      <h2 class="book-author-show">
        <span class="glyphicon glyphicon-user"></span> <%= "#{@comment.book.author}" %>
      </h2>
    <%= form_for(@comment) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Update Comment", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<% provide(:title, 'Add Comment') %>

<div class="row">
  <div class="col-md-12">
      <h1 class="book-name-show">
        <span class="glyphicon glyphicon-book"></span> <%= "#{@book.name}" %>
      </h1>
      <h2 class="book-author-show">
        <span class="glyphicon glyphicon-user"></span> <%= "#{@book.author}" %>
      </h2>
    <%= form_for(@comment) do |f| %>
      <%= f.hidden_field :book_id, :value => @book.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add Comment", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>