config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  match '/signup', to: 'users#new',          via: 'get'
  match '/signup', to: 'users#create',       via: 'post'
  match '/login',  to: 'sessions#new',       via: 'get'
  match '/login',  to: 'sessions#create',    via: 'post'
  match '/logout', to: 'sessions#destroy',   via: 'delete'

  resources :comments

  resources :users do
    resources :comments
  end

  resources :books do
    resources :comments
  end

end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

  default_scope -> { order('updated_at DESC') }
  validates :name,        presence: true, length: { minimum: 3, maximum: 50 }
  validates :author,      presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :logged_in_user,  only: :index
  before_action :admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @books = Book.paginate(page: params[:page], per_page: 15)
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.paginate(page: params[:page], per_page: 2)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "The book has been successfully added"
      redirect_to (books_path)
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "Book updated"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to root_url
  end

  private

    def book_params
      params.require(:book).permit(:name, :author, :description)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_add_comment.html.erb
<%= hidden_field_tag(:book_id, @book.id) %>
<%= submit_tag("Add Comment", class: "btn btn-primary btn-md") %>

app/views/books/_book.html.erb
<tr>
  <td class="book-name">
    <p><span class="glyphicon glyphicon-book"></span> <%= link_to book.name, book %></p>
  </td>
  <td class="book-autor">
    <p><span class="glyphicon glyphicon-user"></span> <%= "#{book.author}" %></p>
  </td>
  <td class="status">
    <p><span class="glyphicon glyphicon-eye-open"></span> In</p>
  </td>

  <% if current_user.admin? %>
  <td>
    <p class="administration">
      <%= link_to "Edit", edit_book_path(book), class: "btn btn-warning btn-xs" %>
      <%= link_to "Delete", book, method: :delete,
                            data: { confirm: "You sure?" },
                            class: 'btn btn-danger btn-xs' %>
    </p>
  </td>
  <% end %>

</tr>

app/views/books/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :author %>
<%= f.text_field :author %>

<%= f.label :description %>
<%= f.text_field :description %>

app/views/books/edit.html.erb
<% provide(:title, 'Edit Book') %>
<h1>Edit Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Update Book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<% if logged_in? %>
<% provide(:title, 'List Books') %>

  <div class="table-responsive">
  <h3><span class="glyphicon glyphicon-star"></span> Top rated books:</h3>
    <table class="table table-hover">
      <thead>
      <tr>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Name</p>
        </td>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Author</p>
        </td>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Status</p>
        </td>

        <% if current_user.admin? %>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Administration</p>
        </td>
        <% end %>

      </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
  </div>

  <div class="table-responsive">
  <h3><span class="glyphicon glyphicon-list"></span> All books:</h3>
    <table class="table table-hover">
      <thead>
      <tr>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Name</p>
        </td>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Author</p>
        </td>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Status</p>
        </td>

        <% if current_user.admin? %>
        <td>
          <p><span class="glyphicon glyphicon-triangle-bottom"></span> Administration</p>
        </td>
        <% end %>

      </tr>
      </thead>
      <tbody>
        <%= render @books %>
      </tbody>
    </table>
  </div>
  <div class="center">
    <%= will_paginate %>
  </div>

<% else %>

  <div class="center jumbotron">
    <h1>Welcome to the FreeBook</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/books/new.html.erb
<% provide(:title, 'Add Book') %>
<h1>Add Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add Book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.name) %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md">
      <h1 class="book-name-show">
        <span class="glyphicon glyphicon-book"></span> <%= "#{@book.name}" %>
      </h1>
      <h2 class="book-author-show">
        <span class="glyphicon glyphicon-user"></span> <%= "#{@book.author}" %>
      </h2>

      <div class="rov">
        <div class="col-md-3">
          <p class="star">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
          </p>
        </div>
        <div class="col-md-2">
          <p class="likes">Likes: <%= "#{10}" %></p>
        </div>
        <div class="col-md-7">
          <p class="btn-click">
            <a href="#" class="btn btn-success" role="button">Take</a>
          </p>
        </div>
      </div>

    <div class="col-md-12">
      <div class="row">
        <div class="col-md-3 center-block">
          <a class="thumbnail">
            <img src="..." data-src="holder.js/100%x180" class="img-thumbnail" alt="Book foto">
          </a>
        </div>
        <div class="col-md-9 description">
          <p>
            <%= "#{@book.description}" %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-12 add-comment-btn">
      <%= form_tag({controller: "comments", action: "new"}, method: "get") do %>
        <%= render 'add_comment' %>
      <% end %>
    </div>
    <div class="col-md-12">
    <%= render @comments %>
      <div class="center">
       <%= will_paginate(@comments) %>
      </div>
    </div>

    <div class="col-md-12">
      <p>history</p>
    </div>

    </div>
  </div>
</div>