config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  match '/signup', to: 'users#new',          via: 'get'
  match '/signup', to: 'users#create',       via: 'post'
  match '/login',  to: 'sessions#new',       via: 'get'
  match '/login',  to: 'sessions#create',    via: 'post'
  match '/logout', to: 'sessions#destroy',   via: 'delete'

  resources :comments

  resources :users do
    resources :comments
  end

  resources :books do
    resources :comments
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <span class="glyphicon glyphicon-education"></span> <%= link_to "FreeBook", root_path %>
  </small>
  <nav>
    <ul>
    <% if logged_in? %>
      <li><span class="glyphicon glyphicon-user"></span> <%= link_to "#{current_user.name}", current_user %></li>
    <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FreeBook", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
            <% if current_user.admin? %>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Admin Menu <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Users", users_path %></li>
                <li><%= link_to "Add Book", new_book_path %></li>
              </ul>
            <% end %>

            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>